repos:
-   repo: https://github.com/nix-community/nixpkgs-fmt
    rev: 8c58125
    hooks:
    -   id: nixpkgs-fmt

- repo: https://github.com/koalaman/shellcheck-precommit
  rev: v0.9.0
  hooks:
    - id: shellcheck
      args: ["-e", "SC1071"]
