---
name: Check
jobs:
    check:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            # - name: Set up Python 3.11
            #   uses: actions/setup-python@v4
            #   with:
            #       python-version: '3.11'
            - name: Pre Commit
              uses: pre-commit/action@v3.0.0
              with:
                  extra_args: --verbose --all-files

