---
name: Check
on: push
jobs:
    check:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Pre Commit
              uses: pre-commit/action@v3.0.0
              with:
                  extra_args: --verbose --all-files

